[package]
name = "hyra-scribe-ledger"
version = "0.1.0"
edition = "2021"
default-run = "hyra-scribe-ledger"

[dependencies]
sled = "0.34"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
openraft = { version = "0.9", features = ["serde", "storage-v2"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
toml = "0.8"
async-trait = "0.1"
socket2 = "0.5"
reqwest = { version = "0.11", features = ["json"] }
clap = { version = "4.5", features = ["derive"] }
aws-config = "1.1"
aws-sdk-s3 = "1.18"
bytes = "1.5"
futures = "0.3"
flate2 = "1.0"
sha2 = "0.10"
hex = "0.4"
prometheus = "0.13"
lazy_static = "1.4"
tracing-appender = "0.2"
fastrand = "2.0"
lru = "0.12"
hostname = "0.3"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
reqwest = { version = "0.11", features = ["json"] }
urlencoding = "2.1"
uuid = { version = "1.0", features = ["v4"] }
nix = { version = "0.27", features = ["signal"] }

[[bench]]
name = "storage_benchmark"
harness = false

[[bench]]
name = "async_storage_benchmark"
harness = false

[[bench]]
name = "http_benchmark"
harness = false

[[bench]]
name = "simple_http_benchmark"
harness = false

[[bench]]
name = "s3_storage_benchmark"
harness = false

[[bench]]
name = "archival_benchmark"
harness = false

[[bench]]
name = "crypto_benchmark"
harness = false

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "data_types" 
path = "examples/data_types.rs"

[[example]]
name = "cli_store"
path = "examples/cli_store.rs"

[[example]]
name = "config_demo"
path = "examples/config_demo.rs"
